Ugh.  On 64-bit machines:
>>> [2] * 1111111111111
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
ValueError: sequence repeat count too large
>>> [2] * 11111111111111111111111111
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
OverflowError: long int too large to convert to int