The generated exceptions with the changes from the last check-in. It sometimes makes py.py, run on top of 2.4.1, crash on exit with:
pypy.interpreter.error.OperationError: [<W_TypeObject(TypeError)>: <UserW_Object
Object() instance of <W_TypeObject(TypeError)>>]