simplified tests because PBC work now last test fails still (probably) because rpython/module/ll_os.py/ll_os_read raises an exception. (errormessage: AttributeError: 'FuncNode' object has no attribute 'write_exceptblock')